### PR TITLE
v0.8.0 - Improve background restoration, multiple listens, drop iOS 9, migrate to Swift 4.2, and more...

### PR DESCRIPTION
**Pull request by JeremyChiang**
### Fixes:
- Background and listen restoration callbacks #120, #156, #181
- Allow trapping and replacing multiple listens, #141
- Fix queueing bug related to discover service and characteristic, #161
- Drop support for iOS 9 #88
- Update to Swift 4.2, #182
- Fixes bugs in demo, #110, #111
- Add main thread safety check, #179

### Changes:
- Removed outdated or soon-to-be-replaced demo projects
- Redo, clean up, and improve Heart Sensor Demo project
- Restrict public access to `Peripheral`
  - The user should never interface with the `Peripheral` directly
    - All interactions should be completed through the Bluejay instance for consistency and stability
  - The user should not be allowed to hold a strong reference to a `Peripheral` object
    - The `Peripheral` objects contain `CBPeripheral` references, and when Bluejay set them to nil they are required to `deinit` and be freed from memory in some cases such as after a disconnection to maintain proper states in the CoreBluetooth stack as well
  - Public APIs in Bluejay as well as the `PeripheralIdentifier` should be sufficient for most usage and design, so `Peripheral` is really not needed anyway (until more compelling feedback)

### Added:
- Add XCGLogger with log to file and monitor log file features
  - Showcased in the updated Heart Sensor demo
  - Will help debug future potential state restoration issues that are difficult to investigate
- Dittojay demo app as a virtual Bluetooth LE heart sensor
  - Can also help test background state restoration

### Summary of Problems:
- Implementation for background and listen restoration was not as comprehensive and effective
- It's easy for newcomers to install multiple listens accidentally and crashing
- Support for iOS 9 is no longer beneficial
- Not yet updated to Swift 4.2
- Bugs in demo apps
- Lack of additional thread safety checks
- Lack of better logging features
- Lack of a way to test background state restoration

### Proposed Solution:
- For specifics, see commit history and discussions in linked issues

### Testing Completed and Required:
- Our existing projects work as expected
- Happy flows for Bluejay and Dittojay demo work as expected

### Screenshots:
- N/A

### CODE REVIEW

**Comment by andeeliao** [comment]
Hey Jeremy, do you have a timeline for when this PR is expected to be merged in?

**Comment by JeremyChiang** [comment]
Hi @andeeliao, I'm still working on it. I am hoping to release it tomorrow before Christmas break, but I need to do more testing. State and background restoration have been challenging to test and to get right. v0.8.0 will also introduce the most API breaking changes thus far, so I have been updating the demo projects and documentation as well to reflect all the improvements coming soon.

If tomorrow doesn't work, we can definitely expect this to come at around early to mid January next year! Let me know if there's any specific features or fixes you are interested in for v0.8.0, so I can spend some time on those areas as well. Thanks!

**Comment by andeeliao** [comment]
Thanks for the quick update Jeremy, that really helps with our planning! 

We're looking specifically at the 2+ devices support, as well as the fix to not crash on the didDiscoverServices event.

**Comment by JeremyChiang** [comment]
Happy to help @andeeliao, especially to users who are already using Bluejay!

By 2+ devices, do you mean multiple listens? If so, that is definitely coming soon, as well as the crashes related queueing service and characteristic discoveries.

However, we don't have plans to support working with more than one Bluetooth LE peripheral in the short term, as that will be another massive project to take on and will require significant effort to adapt the current queueing system for working with multiple peripherals.

We are currently aiming for a 1.0 release that will also include a testing framework/companion app that is similar to LightBlue, but will allow you to do a bit more customization and create your own mock peripherals.

Support for multiple peripherals is probably something for 2.0, but that will be months away. Hope this bit of information helps :)

**Comment by andeeliao** [comment]
Thanks so much!! 

Ah, to clarify I meant only one device at a time, but with the possibility of a history of 2 or more devices on app restore. Is that what you mean by listen?

**Comment by JeremyChiang** [comment]
Hi @andeeliao and to the public as well,

Allen (my boss) has pointed out a good point - my description and mentions of multiple listens can be a bit misleading. Here's my response to Allen, and to everyone as well:

> I need to be more clear on that, so I will update the PR and release notes and docs after this - but no, we won’t support “true” multiple listens where you can have multiple listeners receiving notifications from a single characteristic. What I’ve implemented and have been describing, and wasn’t clear about, is the ability to register listeners on the same characteristic multiple times without crashing by resolving the registration through either trapping (future registrations can’t overwrite an existing listen), or replacing (future registrations will overwrite the current existing listen).

See #141 for more details and discussions on this.

**Comment by JeremyChiang** [comment]
@andeeliao on your question:
> ...but with the possibility of a history of 2 or more devices on app restore...
1. That is not related to the issues of multiple listens
2. I am not 100% sure what you mean, but if you mean setting up restoration paths for different devices, because different devices might wake up the same app in the background (considering they've all been connected to once using your app), then that should work starting v0.8

If point 2 is indeed what you want to do, that can be done using v0.8 from my understanding, but will require some tricky setup. I can help you more with that on the side if that's what you're looking for.

**Comment by andeeliao** [comment]
@JeremyChiang thanks for the clarification! Yes, that is what I'm looking to do. Sounds good, I'll take a look when this gets merged in! Thanks for all your hard work :)

**Comment by JeremyChiang** [comment]
No problem @andeeliao! I have filed #185 to keep track of your feedback. I think that is a very good test case, so for the next few days we can discuss more on that specific feature over there in that issue.

**Pull request merged**
