### PR TITLE
Update to Xcode 9 recommended and migration to Swift 4

### PR DESCRIPTION
**Pull request by larryonoff**

### CODE REVIEW

**Comment by JeremyChiang** [comment]
@larryonoff I originally wanted to just change the line `@objc(BJListenCacheCoding` to `@objc(BluejayListenCacheCoding`, but decided to just try and use Codable instead and remove all the encoding and decoding nonsense.

This also replaced a bunch of force-unwrapped encoding/decoding code with try/catch, which is a little safer, despite it's fairly unlikely to ever happen – hopefully.

I've also renamed the private function `attemptListenRestoration` to `requestListenRestoration`, as the new name fits the `try` statement nicer, because "try" and "attempt" one after another reads a bit redundant to me.

**Comment by larryonoff** [comment]
@JeremyChiang thanks for help! Looking forward to the swift 4 release.

**Comment by larryonoff** [comment]
I think `Codable` solution is the best.

About prefixes. `BJ*` prefix instead of `Bluejay*`prefix fits Apple recommendation. See https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPFrameworks/Concepts/CreationGuidelines.html and https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/CodingGuidelines/Articles/NamingBasics.html
```
Typical prefixes include the first couple of letters or an acronym of your framework name. For example, functions in the Core Graphics framework use the prefix “CG”.
```
I remember that there should be three letters in prefix, but wasn't able to find proof.

My opinion that we should not make prefixes too long, but unique.

**Comment by JeremyChiang** [comment]
@nbrooke @apike if this looks good to you as well, we can merge this and I'll update our pod. Thanks!

**Comment by nbrooke** [comment]
The letter prefixes are pretty specific to ObjC, you'll note that both those documents were last revised in 2013, and thus all the advice basically predates Swift. Almost no Swift code i've seen uses 2 or 3 letter prefixes for anything, because the main reason for doing it on ObjC (you NEED to add those prefixes to EVERYTHING because it's all in the same namespace, so you want them short because you re going to be typing them all the time) does not apply to Swift, due to Swift frameworks always being modules.

In general, this change looks good to me. I particularly like the switch to Codable for the listen cache stuff.

**Comment by larryonoff** [comment]
@nbrooke I absolutely agree about Swift. But there're some cases that have to be expanded into ObjC. This's why I suggest using 3-letter prefix rule for swift classes that expanded into ObjC and only via `@objc()`.

**Comment by nbrooke** [comment]
I don't think we need to worry about that too much, Bluejay uses enough Swift specific features that I not sure it could be usefully exposed to ObjC anyway, I think the only reason that definition was there is because the class needed some ObjC name for the keyed archiver to work, but no client of the app would ever be referencing that class by it's ObjC name, so the name can be arbitrarily complicated, no reason for  a short prefix.

**Pull request merged**
